services:
  tgbot:
    build: .
    container_name: wb_tg_bot
    restart: always
    volumes:
      - ./resources:/app/resources
      - ./convo-data:/app/convo-data
      - ./output:/app/output
      - ./db.json:/app/db.json
    environment:
      - NODE_ENV=production